### ISSUE TITLE
问个和博客不搭界的问题

### ISSUE THREAD

**Issue by XingXiaoWu** [CBCzed/CBCzed.github.io#1]
tracekit这个库老哥应该用过？
有没有demo借看看。。

**Comment by CBCzed** [comment]
tracekit的用法在[npm](https://www.npmjs.com/package/tracekit#usage)上有了说明了；
个人常用于错误日志上报错误，通常会单独封装一个方法
`import TraceKit from 'tracekit'
TraceKit.report.subscribe(function logger (errorReport) {
  // errorReport 为错误对象
  if (errorReport.mode === 'stack') {
    fetch({
      url: url,
      method: 'post',
      data: {
        error: {
          name: errorReport.name,
          message: errorReport.message,
          fileName: errorReport.stack[0].url.split(webUrl)[1],
          line: errorReport.stack[0].line,
          column: errorReport.stack[0].column
        }
      }
    })
  }
})
const reportError = TraceKit.report
export { reportError }`
使用, 需要借助try{}catch(e){}：
`import { reportError } from './utils/reportError'
try {
  /*
   * your application code here
   *
   */
  throw new Error('oops');
} catch (e) {
  reportError(e); //error with stack trace gets normalized and sent to subscriber
}`

**Comment by XingXiaoWu** [comment]
他这个不支持npm引入吧。。。我npm引入后，import都直接报错
```
import TraceKit from 'tracekit'
```

**Comment by CBCzed** [comment]
嗯...，我这边是npm安装的，使用也没啥问题，npm不行的话，你可以使用 bower

**Comment by XingXiaoWu** [comment]
好的，非常感谢，我再看看
